# Generated by Django 5.1.6 on 2025-02-11 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_liga', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('posicion_favorita', models.CharField(blank=True, choices=[('1', 'Arquero'), ('2', 'Defensor'), ('3', 'Mediocampista'), ('4', 'Delantero')], max_length=1, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='AppFulbo.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField(blank=True, null=True)),
                ('cancha', models.CharField(max_length=15)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='AppFulbo.liga')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuntajePartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(default=0.0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_partidos', to='AppFulbo.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_partidos', to='AppFulbo.partido')),
            ],
        ),
    ]
