# Generated by Django 5.1.6 on 2025-02-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
