# Generated by Django 5.1.6 on 2025-02-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0004_alter_jugador_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jugador',
            unique_together={('apodo', 'liga')},
        ),
    ]
