# Generated by Django 5.1.6 on 2025-02-18 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0006_alter_liga_nombre_liga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liga',
            name='presidentes',
            field=models.ManyToManyField(related_name='ligas_presididas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liga',
            name='nombre_liga',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
