# Generated by Django 5.1.6 on 2025-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0007_liga_descripcion_liga_presidentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='nombre_liga',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
