# Generated by Django 5.1.6 on 2025-02-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0008_alter_liga_nombre_liga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
