# Generated by Django 5.1.6 on 2025-02-19 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0010_alter_liga_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='super_presidentes',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='ligas_super_presididas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
