# Generated by Django 5.1.6 on 2025-02-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0012_remove_liga_super_presidentes_liga_super_presidente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liga',
            name='super_presidente',
        ),
    ]
