# Generated by Django 5.1.6 on 2025-02-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0015_jugador_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el jugador está activo en la liga.'),
        ),
    ]
