# Generated by Django 5.1.6 on 2025-03-01 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0019_mensaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudUnionLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_union', to='AppFulbo.liga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_union', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'liga')},
            },
        ),
    ]
