# Generated by Django 5.1.6 on 2025-03-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0020_solicitudunionliga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntajepartido',
            name='puntaje',
            field=models.FloatField(null=True),
        ),
    ]
