# Generated by Django 5.1.6 on 2025-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0022_alter_jugador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('MSG', 'Mensaje'), ('SOL', 'Solicitud'), ('PP', 'Puntuat Partido')], max_length=3),
        ),
    ]
