# Generated by Django 5.1.6 on 2025-03-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0023_alter_notificacion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='presidentes',
            field=models.ManyToManyField(related_name='ligas_presididas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PuntuacionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_pendiente', to='AppFulbo.jugador')),
                ('puntaje_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuacion_pendiente', to='AppFulbo.puntajepartido')),
            ],
        ),
    ]
