# Generated by Django 5.1.6 on 2025-03-08 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0024_alter_liga_presidentes_puntuacionpendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacionpendiente',
            name='liga',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_pendientes', to='AppFulbo.liga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntuacionpendiente',
            name='partido',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_pendientes', to='AppFulbo.partido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puntuacionpendiente',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_jugador', to='AppFulbo.jugador'),
        ),
        migrations.AlterField(
            model_name='puntuacionpendiente',
            name='puntaje_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_pendientes', to='AppFulbo.puntajepartido'),
        ),
    ]
