# Generated by Django 5.1.6 on 2025-03-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulbo', '0025_puntuacionpendiente_liga_puntuacionpendiente_partido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntajepartido',
            old_name='puntaje',
            new_name='suma_puntajes',
        ),
        migrations.AddField(
            model_name='puntajepartido',
            name='cant_puntajes',
            field=models.FloatField(default=0),
        ),
    ]
